// <auto-generated />
namespace RentedMovieOneValid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingNewColumnStock_AvailableWithRequiredToMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingNewColumnStock_AvailableWithRequiredToMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "201905060658352_AddingNewColumnStock_AvailableWithRequiredToMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
